#!/bin/bash

#SBATCH --job-name="process_gmos_data_test_2017"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=24:00:00
#SBATCH --array=0
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=process_gmos_data_test_2017_%A_%a.out

module load gnu/9.2.0
module load wgrib/1.8.1.0b

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
INPUT_DIR_NAME="/scratch2/STI/mdl-sti/John.Crockett/firewx_data/gmos/fdr"
OUTPUT_DIR_NAME="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/gridded_gfs_mos/processed/test"
WGRIB2_EXE_NAME="wgrib"

FIRST_INIT_TIME_STRINGS=("2017-01-01-00")
LAST_INIT_TIME_STRINGS=("2017-01-31-18")

first_init_time_string="${FIRST_INIT_TIME_STRINGS[$SLURM_ARRAY_TASK_ID]}"
last_init_time_string="${LAST_INIT_TIME_STRINGS[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/process_gridded_mos_data.py" \
--input_tdlpack_dir_name="${INPUT_DIR_NAME}" \
--first_init_time_string="${first_init_time_string}" \
--last_init_time_string="${last_init_time_string}" \
--process_00z_runs=1 \
--process_12z_runs=0 \
--tar_output_files=1 \
--output_zarr_dir_name="${OUTPUT_DIR_NAME}"
