#!/bin/bash

#SBATCH --job-name="evaluate_model_ungridded_by_month"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=04:00:00
#SBATCH --array=0-11
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_model_ungridded_by_month_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment11_crps_all_targets"
TARGET_NORM_FILE_NAME="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed/normalization_params_20170101-20211220.nc"

NWP_LEAD_TIME_COUNTS=("1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4")
LAG_TIME_COUNTS=("1" "1" "1" "1" "2" "2" "2" "2" "3" "3" "3" "3" "4" "4" "4" "4")

BEST_MODEL_INDEX=2

num_nwp_lead_times=${NWP_LEAD_TIME_COUNTS[$BEST_MODEL_INDEX]}
num_lag_times=${LAG_TIME_COUNTS[$BEST_MODEL_INDEX]}

model_dir_name="${TOP_MODEL_DIR_NAME}/num-nwp-lead-times=${num_nwp_lead_times}_num-lag-times=${num_lag_times}"
echo $model_dir_name

MONTHS=("01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12")

python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
--input_prediction_dir_name="${model_dir_name}/validation_full_grid" \
--init_time_limit_strings "2022-01-01-00" "2022-12-31-18" \
--num_bootstrap_reps=1 \
--evaluate_month=${MONTHS[$SLURM_ARRAY_TASK_ID]} \
--target_field_names "temperature_2m_agl_kelvins" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "dewpoint_2m_agl_kelvins" "wind_gust_10m_agl_m_s01" \
--input_target_norm_file_name="${TARGET_NORM_FILE_NAME}" \
--num_relia_bins_by_target 115 80 80 115 80 \
--min_relia_bin_edge_by_target -60 -40 -40 -80 0 \
--max_relia_bin_edge_by_target 55 40 40 35 80 \
--per_grid_cell=0 \
--keep_it_simple=0 \
--output_file_name_or_pattern="${model_dir_name}/validation_full_grid/ungridded_evaluation.nc"
