#!/bin/bash

#SBATCH --job-name="apply_neural_nets_validation"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=24:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_validation_%A.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_EXAMPLE_DIR_NAME="/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_models/experiment23_full_domain"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment22_regional_models"

REGION_NAMES=("region1-1" "region2-1" "region3-1" "region4-1" "region5-1" "region1-2" "region2-2" "region3-2" "region4-2" "region5-2" "region1-3" "region2-3" "region3-3" "region4-3" "region5-3" "region1-4" "region2-4" "region3-4" "region4-4" "region5-4" "region1-5" "region2-5" "region3-5" "region4-5" "region5-5" "region1-6" "region2-6" "region3-6" "region4-6" "region5-6" "region1-7" "region2-7" "region3-7" "region4-7" "region5-7" "region1-8" "region2-8" "region3-8" "region4-8" "region5-8")
model_file_names_one_string=""

for this_region_name in "${REGION_NAMES[@]}"; do
    model_file_names_one_string="${model_file_names_one_string} ${TOP_MODEL_DIR_NAME}/${this_region_name}/model.weights.h5"
done

example_dir_name="${TOP_EXAMPLE_DIR_NAME}/npz_example_files"

python3 -u "${CODE_DIR_NAME}/apply_many_single_patch_nns_to_example_files.py" \
--input_model_file_names ${model_file_names_one_string} \
--input_example_dir_name="${example_dir_name}" \
--first_init_time_string="2022-01-01-00" \
--last_init_time_string="2022-12-31-18" \
--use_ema=0 \
--save_ensemble_mean_only=1 \
--output_dir_name="${TOP_MODEL_DIR_NAME}/stitched/validation_full_grid"
