#!/bin/bash

#SBATCH --job-name="evaluate_model_gridded_simple"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=12:00:00
#SBATCH --array=8
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_model_gridded_simple_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TARGET_NORM_FILE_NAME="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed/normalization_params_20170101-20211220.nc"

NWP_MODEL_NAMES=("ecmwf" "gefs" "gfs" "gridded_gfs_mos" "gridded_lamp" "hrrr" "nam" "nam_nest" "rap" "wrf_arw")
LEAD_TIME_STRINGS=("48h" "48h" "48h" "48h" "24h" "48h" "51h" "48h" "48h" "48h")

nwp_model_name="${NWP_MODEL_NAMES[$SLURM_ARRAY_TASK_ID]}"
lead_time_string="${LEAD_TIME_STRINGS[$SLURM_ARRAY_TASK_ID]}"

python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
--input_prediction_dir_name="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/${nwp_model_name}/processed/interp_to_nbm_grid/prediction_files_${lead_time_string}" \
--first_init_time_string_by_period "2022-01-01-00" \
--last_init_time_string_by_period "2022-12-31-18" \
--num_bootstrap_reps=1 \
--target_field_names "temperature_2m_agl_kelvins" \
--input_target_norm_file_name="${TARGET_NORM_FILE_NAME}" \
--num_relia_bins_by_target 65 \
--min_relia_bin_edge_by_target -30 \
--max_relia_bin_edge_by_target 35 \
--per_grid_cell=1 \
--keep_it_simple=1 \
--output_file_name="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/${nwp_model_name}/processed/interp_to_nbm_grid/prediction_files_${lead_time_string}/validation_temperature/gridded_evaluation_simple.nc"
