#!/bin/bash

#SBATCH --job-name="apply_neural_nets_validation"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=36:00:00
#SBATCH --array=0-19
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_validation_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_EXAMPLE_DIR_NAME="/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_models/experiment23_full_domain"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment23_full_domain"

MODEL_DESCRIPTION_STRINGS=("adamw/random_seed0" "adamw/random_seed1" "adamw/random_seed2" "adamw/random_seed3" "adamw/random_seed4" "adamw_cycle050/random_seed0" "adamw_cycle050/random_seed1" "adamw_cycle050/random_seed2" "adamw_cycle050/random_seed3" "adamw_cycle050/random_seed4" "adamw_cycle100/random_seed0" "adamw_cycle100/random_seed1" "adamw_cycle100/random_seed2" "adamw_cycle100/random_seed3" "adamw_cycle100/random_seed4" "adamw_cycle200/random_seed0" "adamw_cycle200/random_seed1" "adamw_cycle200/random_seed2" "adamw_cycle200/random_seed3" "adamw_cycle200/random_seed4")

model_dir_name="${TOP_MODEL_DIR_NAME}/${MODEL_DESCRIPTION_STRINGS[$SLURM_ARRAY_TASK_ID]}"
example_dir_name="${TOP_EXAMPLE_DIR_NAME}/npz_example_files"
echo $model_dir_name

python3 -u "${CODE_DIR_NAME}/apply_neural_net_to_example_files.py" \
--input_model_file_name="${model_dir_name}/model.weights.h5" \
--input_example_dir_name="${example_dir_name}" \
--first_init_time_string="2022-01-01-00" \
--last_init_time_string="2022-12-31-18" \
--patches_to_full_grid=1 \
--single_patch_start_row_2pt5km=-1 \
--single_patch_start_column_2pt5km=-1 \
--use_ema=0 \
--save_ensemble_mean_only=1 \
--use_trapezoidal_weighting=0 \
--patch_overlap_size_2pt5km_pixels=64 \
--output_dir_name="${model_dir_name}/validation_full_grid"
