#!/bin/bash

#SBATCH --job-name="apply_isotonic_regression_validation"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=04:00:00
#SBATCH --array=0-15
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_isotonic_regression_validation_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment18_high_res_ensemble"
TARGET_NORM_FILE_NAME="/scratch1/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed/normalization_params_20170101-20211220.nc"

MODEL_NAME_SETS_ONE_STRING=("ensemble_hrrr_wrf-arw" "ensemble_hrrr_nam-nest" "ensemble_hrrr_gridded-gfs-mos" "ensemble_wrf-arw_nam-nest" "ensemble_wrf-arw_gridded-gfs-mos" "ensemble_nam-nest_gridded-gfs-mos" "hrrr_wrf-arw_nam-nest" "hrrr_wrf-arw_gridded-gfs-mos" "hrrr_nam-nest_gridded-gfs-mos" "wrf-arw_nam-nest_gridded-gfs-mos" "ensemble_hrrr_wrf-arw_nam-nest" "ensemble_hrrr_wrf-arw_gridded-gfs-mos" "ensemble_hrrr_nam-nest_gridded-gfs-mos" "ensemble_wrf-arw_nam-nest_gridded-gfs-mos" "hrrr_wrf-arw_nam-nest_gridded-gfs-mos" "ensemble_hrrr_wrf-arw_nam-nest_gridded-gfs-mos")

model_dir_name="${TOP_MODEL_DIR_NAME}/nwp-inputs=${MODEL_NAME_SETS_ONE_STRING[$SLURM_ARRAY_TASK_ID]}"
echo $model_dir_name

python3 -u "${CODE_DIR_NAME}/apply_bias_correction.py" \
--input_prediction_dir_name="${model_dir_name}/validation_full_grid" \
--init_time_limit_strings "2022-01-01-00" "2022-12-31-18" \
--isotonic_model_file_names "${model_dir_name}/training_full_grid/isotonic_regression/isotonic_regression_temperature_2m_agl_kelvins.dill" "${model_dir_name}/training_full_grid/isotonic_regression/isotonic_regression_u_wind_10m_agl_m_s01.dill" "${model_dir_name}/training_full_grid/isotonic_regression/isotonic_regression_v_wind_10m_agl_m_s01.dill" "${model_dir_name}/training_full_grid/isotonic_regression/isotonic_regression_dewpoint_2m_agl_kelvins.dill" "${model_dir_name}/training_full_grid/isotonic_regression/isotonic_regression_wind_gust_10m_agl_m_s01.dill" \
--output_prediction_dir_name="${model_dir_name}/validation_full_grid/isotonic_regression"
