#!/bin/bash

#SBATCH --job-name="do_bias_clustering"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=12:00:00
#SBATCH --array=0-79
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=do_bias_clustering_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment18_high_res_ensemble"

MODEL_NAME_SETS_ONE_STRING=("ensemble_hrrr_wrf-arw" "ensemble_hrrr_nam-nest" "ensemble_hrrr_gridded-gfs-mos" "ensemble_wrf-arw_nam-nest" "ensemble_wrf-arw_gridded-gfs-mos" "ensemble_nam-nest_gridded-gfs-mos" "hrrr_wrf-arw_nam-nest" "hrrr_wrf-arw_gridded-gfs-mos" "hrrr_nam-nest_gridded-gfs-mos" "wrf-arw_nam-nest_gridded-gfs-mos" "ensemble_hrrr_wrf-arw_nam-nest" "ensemble_hrrr_wrf-arw_gridded-gfs-mos" "ensemble_hrrr_nam-nest_gridded-gfs-mos" "ensemble_wrf-arw_nam-nest_gridded-gfs-mos" "hrrr_wrf-arw_nam-nest_gridded-gfs-mos" "ensemble_hrrr_wrf-arw_nam-nest_gridded-gfs-mos")
TARGET_FIELD_NAMES=("temperature_2m_agl_kelvins" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "dewpoint_2m_agl_kelvins" "wind_gust_10m_agl_m_s01")

num_rows=${#MODEL_NAME_SETS_ONE_STRING[@]}
num_columns=${#TARGET_FIELD_NAMES[@]}

i=$(( SLURM_ARRAY_TASK_ID / num_columns ))
j=$(( SLURM_ARRAY_TASK_ID % num_columns ))

target_field_name=${TARGET_FIELD_NAMES[$j]}
model_dir_name="${TOP_MODEL_DIR_NAME}/nwp-inputs=${MODEL_NAME_SETS_ONE_STRING[$i]}"
echo $model_dir_name

if [ "$target_field_name" = "temperature_2m_agl_kelvins" ]; then
    bias_discretization_intervals="0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000"
elif [ "$target_field_name" = "dewpoint_2m_agl_kelvins" ]; then
    bias_discretization_intervals="0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000"
else
    bias_discretization_intervals="0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50"
fi

python3 -u "${CODE_DIR_NAME}/do_bias_clustering.py" \
--input_gridded_eval_file_arg_name="${model_dir_name}/training_full_grid/gridded_evaluation_${target_field_name}.nc" \
--min_cluster_size_px=250 \
--target_field_name="${target_field_name}" \
--bias_discretization_intervals ${bias_discretization_intervals} \
--buffer_distance_px=6 \
--do_backwards_clustering=1 \
--cluster_ssdiff_instead_of_bias=0 \
--main_output_file_name="${model_dir_name}/training_full_grid/isotonic_regression/bias_clustering_${target_field_name}.nc" \
--output_figure_file_name="${model_dir_name}/training_full_grid/isotonic_regression/bias_clustering_${target_field_name}.jpg"
