#!/bin/bash

#SBATCH --job-name="do_bias_clustering"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=12:00:00
#SBATCH --array=4,24,27-29,32-34,37,39
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=do_bias_clustering_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment21_cosine_annealing_and_weight_decay"

OPTIMIZER_NAMES=("adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "adamw" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion" "lion")
WEIGHT_DECAY_VALUES=("0.000010" "0.000030" "0.000050" "0.000070" "0.000090" "0.000110" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000010" "0.000030" "0.000050" "0.000070" "0.000090" "0.000110" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000" "0.000000")
ANNEALING_STRINGS=("none" "none" "none" "none" "none" "none" "050epochs-min0.00001" "050epochs-min0.00004" "050epochs-min0.00007" "050epochs-min0.00010" "100epochs-min0.00001" "100epochs-min0.00004" "100epochs-min0.00007" "100epochs-min0.00010" "150epochs-min0.00001" "150epochs-min0.00004" "150epochs-min0.00007" "150epochs-min0.00010" "200epochs-min0.00001" "200epochs-min0.00004" "200epochs-min0.00007" "200epochs-min0.00010" "none" "none" "none" "none" "none" "none" "050epochs-min0.00001" "050epochs-min0.00004" "050epochs-min0.00007" "050epochs-min0.00010" "100epochs-min0.00001" "100epochs-min0.00004" "100epochs-min0.00007" "100epochs-min0.00010" "150epochs-min0.00001" "150epochs-min0.00004" "150epochs-min0.00007" "150epochs-min0.00010" "200epochs-min0.00001" "200epochs-min0.00004" "200epochs-min0.00007" "200epochs-min0.00010")

optimizer_name=${OPTIMIZER_NAMES[$SLURM_ARRAY_TASK_ID]}
weight_decay_value=${WEIGHT_DECAY_VALUES[$SLURM_ARRAY_TASK_ID]}
annealing_string=${ANNEALING_STRINGS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/optimizer=${optimizer_name}_weight-decay=${weight_decay_value}_annealing=${annealing_string}"
echo $model_dir_name

TARGET_FIELD_NAMES=("temperature_2m_agl_kelvins" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "dewpoint_2m_agl_kelvins" "wind_gust_10m_agl_m_s01")

for target_field_name in "${TARGET_FIELD_NAMES[@]}"; do
    if [ "$target_field_name" = "temperature_2m_agl_kelvins" ]; then
        bias_discretization_intervals="0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000"
    elif [ "$target_field_name" = "dewpoint_2m_agl_kelvins" ]; then
        bias_discretization_intervals="0.100 0.200 0.300 0.400 0.500 0.600 0.700 0.800 0.900 1.000"
    else
        bias_discretization_intervals="0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50"
    fi

    python3 -u "${CODE_DIR_NAME}/do_bias_clustering.py" \
    --input_gridded_eval_file_arg_name="${model_dir_name}/training_full_grid/gridded_evaluation_${target_field_name}.nc" \
    --min_cluster_size_px=250 \
    --target_field_name="${target_field_name}" \
    --bias_discretization_intervals ${bias_discretization_intervals} \
    --buffer_distance_px=6 \
    --do_backwards_clustering=1 \
    --cluster_ssdiff_instead_of_bias=0 \
    --main_output_file_name="${model_dir_name}/training_full_grid/isotonic_regression/bias_clustering_${target_field_name}.nc" \
    --output_figure_file_name="${model_dir_name}/training_full_grid/isotonic_regression/bias_clustering_${target_field_name}.jpg"
done
