#!/bin/bash

#SBATCH --job-name="evaluate_neural_nets_ungridded"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=12:00:00
#SBATCH --array=0-71%36
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=evaluate_neural_nets_ungridded_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment15_bells_and_whistles"
TARGET_NORM_FILE_NAME="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed/normalization_params_20170101-20211220.nc"

CONVNEXT_V2_FLAGS=("0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1")
BOTTLENECK_LAYER_COUNTS=("1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "1" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "2" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3" "3")
SPECTRAL_NORM_FLAGS=("0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1" "0" "0" "0" "0" "0" "0" "1" "1" "1" "1" "1" "1")
DROPOUT_STRATEGIES=("none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable" "none" "none" "constant0.1" "constant0.1" "variable" "variable")
RESIDUAL_NORM_FLAGS=("0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1" "0" "1")

convnext_v2_flag=${CONVNEXT_V2_FLAGS[$SLURM_ARRAY_TASK_ID]}
num_bottleneck_layers=${BOTTLENECK_LAYER_COUNTS[$SLURM_ARRAY_TASK_ID]}
spectral_norm_flag=${SPECTRAL_NORM_FLAGS[$SLURM_ARRAY_TASK_ID]}
dropout_strategy=${DROPOUT_STRATEGIES[$SLURM_ARRAY_TASK_ID]}
residual_norm_flag=${RESIDUAL_NORM_FLAGS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/convnext-v2=${convnext_v2_flag}_num-bottleneck-layers=${num_bottleneck_layers}_spectral-norm=${spectral_norm_flag}_dropout-strategy=${dropout_strategy}_residual-norm=${residual_norm_flag}"
echo $model_dir_name

if [ "$target_field_name" = "temperature_2m_agl_kelvins" ]; then
    num_relia_bins=115
    min_relia_bin_edge=-60
    max_relia_bin_edge=55
elif [ "$target_field_name" = "u_wind_10m_agl_m_s01" ]; then
    num_relia_bins=80
    min_relia_bin_edge=-40
    max_relia_bin_edge=40
elif [ "$target_field_name" = "v_wind_10m_agl_m_s01" ]; then
    num_relia_bins=80
    min_relia_bin_edge=-40
    max_relia_bin_edge=40
elif [ "$target_field_name" = "dewpoint_2m_agl_kelvins" ]; then
    num_relia_bins=115
    min_relia_bin_edge=-80
    max_relia_bin_edge=35
else
    num_relia_bins=80
    min_relia_bin_edge=0
    max_relia_bin_edge=80
fi

python3 -u "${CODE_DIR_NAME}/evaluate_model.py" \
--input_prediction_dir_name="${model_dir_name}/validation_full_grid/without_ema" \
--init_time_limit_strings "2022-01-01-00" "2022-12-31-18" \
--num_bootstrap_reps=1 \
--target_field_names "temperature_2m_agl_kelvins" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "dewpoint_2m_agl_kelvins" "wind_gust_10m_agl_m_s01" \
--input_target_norm_file_name="${TARGET_NORM_FILE_NAME}" \
--num_relia_bins_by_target 115 80 80 115 80 \
--min_relia_bin_edge_by_target -60 -40 -40 -80 0 \
--max_relia_bin_edge_by_target 55 40 40 35 80 \
--per_grid_cell=0 \
--keep_it_simple=0 \
--output_file_name_or_pattern="${model_dir_name}/validation_full_grid/without_ema/ungridded_evaluation_${target_field_name}.nc"
