#!/bin/bash

#SBATCH --job-name="plot_error_distributions_tails_only"
#SBATCH --partition="bigmem"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=04:00:00
#SBATCH --array=0-4
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_error_distributions_tails_only_%A_%a.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
PREDICTION_DIR_NAME="/scratch1/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_project/nbm_data/processed/prediction_files/experiment19_patch"
TARGET_NORM_FILE_NAME="/scratch1/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed/normalization_params_20170101-20211220.nc"

TARGET_FIELD_NAMES=("temperature_2m_agl_kelvins" "u_wind_10m_agl_m_s01" "v_wind_10m_agl_m_s01" "dewpoint_2m_agl_kelvins" "wind_gust_10m_agl_m_s01")
target_field_name=${TARGET_FIELD_NAMES[$SLURM_ARRAY_TASK_ID]}

if [ "$target_field_name" = "temperature_2m_agl_kelvins" ]; then
    num_bins=115
    min_bin_edge=-60
    max_bin_edge=55
elif [ "$target_field_name" = "u_wind_10m_agl_m_s01" ]; then
    num_bins=80
    min_bin_edge=-40
    max_bin_edge=40
elif [ "$target_field_name" = "v_wind_10m_agl_m_s01" ]; then
    num_bins=80
    min_bin_edge=-40
    max_bin_edge=40
elif [ "$target_field_name" = "dewpoint_2m_agl_kelvins" ]; then
    num_bins=115
    min_bin_edge=-80
    max_bin_edge=35
else
    num_bins=80
    min_bin_edge=0
    max_bin_edge=80
fi

python3 -u "${CODE_DIR_NAME}/plot_error_distributions.py" \
--input_prediction_dir_name="${PREDICTION_DIR_NAME}" \
--init_time_limit_strings "2022-01-01-00" "2022-12-31-18" \
--target_field_names ${target_field_name} \
--num_bins_by_target ${num_bins} \
--min_bin_edge_by_target ${min_bin_edge} \
--max_bin_edge_by_target ${max_bin_edge} \
--violin_or_box_plots=-1 \
--left_tail_percentile=0.5 \
--right_tail_percentile=99.5 \
--max_num_pdf_values=1000000 \
--output_dir_name="${PREDICTION_DIR_NAME}/validation/error_distributions"
