#!/bin/tcsh

#SBATCH --job-name="get_norm_params_for_nwp"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="gpuwf"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=get_norm_params_for_nwp_%A.out

conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
set OUTPUT_FILE_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/normalization_params_20221101-20230531.nc"

python3 -u "${CODE_DIR_NAME}/get_norm_params_for_nwp.py" \
--model_names "nam" "rap" "gfs" "gefs" "gridded_lamp" "wrf_arw" \
--input_dir_name_by_model "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/nam/processed/interp_to_nbm_grid" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/rap/processed/interp_to_nbm_grid" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/gfs/processed/interp_to_nbm_grid" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/gefs/processed/interp_to_nbm_grid" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/gridded_lamp/processed/interp_to_nbm_grid" "/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data/wrf_arw/processed/interp_to_nbm_grid" \
--first_init_time_string="2022-11-01-00" \
--last_init_time_string="2023-05-31-23" \
--num_init_times_by_model 35 210 35 35 210 18 \
--num_quantiles=1001 \
--num_sample_values_per_file=4000 \
--output_norm_file_name="${OUTPUT_FILE_NAME}"
