#!/bin/bash

#SBATCH --job-name="apply_neural_nets_validation"
#SBATCH --partition="fge"
#SBATCH --account="mdl-sti"
#SBATCH --qos="gpuwf"
#SBATCH --nodes=1
#SBATCH --ntasks=8           # 8 tasks per node
#SBATCH --cpus-per-task=2
#SBATCH --ntasks-per-node=8  # 8 GPUs per node
#SBATCH --exclusive
#SBATCH --time=08:00:00
#SBATCH --array=0-15
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_validation_%A_%a.out

module load cuda/12.3.1
conda init
conda activate base

echo `which conda`
echo `which python`
echo `which python3`

# PATH=/usr/local/cuda/bin:$PATH
echo $PATH

CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_standalone/ml_for_national_blend"
TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml_for_national_blend_models/experiment11_with_closer_lead_times"
TARGET_DIR_NAME="/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/urma_data_final/processed"

NWP_LEAD_TIME_COUNTS=("1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4" "1" "2" "3" "4")
LAG_TIME_COUNTS=("1" "1" "1" "1" "2" "2" "2" "2" "3" "3" "3" "3" "4" "4" "4" "4" "1" "1" "1" "1" "2" "2" "2" "2" "3" "3" "3" "3" "4" "4" "4" "4" "1" "1" "1" "1" "2" "2" "2" "2" "3" "3" "3" "3" "4" "4" "4" "4" "1" "1" "1" "1" "2" "2" "2" "2" "3" "3" "3" "3" "4" "4" "4" "4")
INIT_HOURS=("00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "00" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "06" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "12" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18" "18")

num_nwp_lead_times=${NWP_LEAD_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
num_lag_times=${LAG_TIME_COUNTS[$SLURM_ARRAY_TASK_ID]}
init_hour=${INIT_HOURS[$SLURM_ARRAY_TASK_ID]}

model_dir_name="${TOP_MODEL_DIR_NAME}/num-nwp-lead-times=${num_nwp_lead_times}_num-lag-times=${num_lag_times}"
echo $model_dir_name

INIT_DATE_STRINGS=("2022-01-01" "2022-01-06" "2022-01-11" "2022-01-16" "2022-01-21" "2022-01-26" "2022-01-31" "2022-02-05" "2022-02-10" "2022-02-15" "2022-02-20" "2022-02-25" "2022-03-02" "2022-03-07" "2022-03-12" "2022-03-17" "2022-03-22" "2022-03-27" "2022-04-01" "2022-04-06" "2022-04-11" "2022-04-16" "2022-04-21" "2022-04-26" "2022-05-01" "2022-05-06" "2022-05-11" "2022-05-16" "2022-05-21" "2022-05-26" "2022-05-31" "2022-06-05" "2022-06-10" "2022-06-15" "2022-06-20" "2022-06-25" "2022-06-30" "2022-07-05" "2022-07-10" "2022-07-15" "2022-07-20" "2022-07-25" "2022-07-30" "2022-08-04" "2022-08-09" "2022-08-14" "2022-08-19" "2022-08-24" "2022-08-29" "2022-09-03" "2022-09-08" "2022-09-13" "2022-09-18" "2022-09-23" "2022-09-28" "2022-10-03" "2022-10-08" "2022-10-13" "2022-10-18" "2022-10-23" "2022-10-28" "2022-11-02" "2022-11-07" "2022-11-12" "2022-11-17" "2022-11-22" "2022-11-27" "2022-12-02" "2022-12-07" "2022-12-12" "2022-12-17" "2022-12-22" "2022-12-27")

for this_init_date_string in "${INIT_DATE_STRINGS[@]}"; do
    python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
    --input_model_file_name="${model_dir_name}/model.weights.h5" \
    --init_time_string="${this_init_date_string}-${init_hour}" \
    --nwp_model_names "ensemble" "hrrr" "nam_nest" \
    --input_nwp_directory_names "/scratch2/STI/mdl-sti/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/ensemble_all_vars/processed/interp_to_nbm_grid" "/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/hrrr/processed/interp_to_nbm_grid" "/scratch2/NCEPDEV/stmp/Ryan.Lagerquist/ml_for_national_blend_project/nwp_model_data_final/nam_nest/processed/interp_to_nbm_grid" \
    --input_target_dir_name="${TARGET_DIR_NAME}" \
    --patches_to_full_grid=1 \
    --patch_overlap_size_2pt5km_pixels=144 \
    --output_dir_name="${model_dir_name}/validation_full_grid"
done
